# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto_gen/blinky.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto_gen/blinky.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto_gen/blinky.proto\x1a\x1bgoogle/protobuf/empty.proto\")\n\rSetLEDRequest\x12\x0c\n\x04line\x18\x01 \x01(\x05\x12\n\n\x02on\x18\x02 \x01(\x08\x32@\n\x0c\x42linkService\x12\x30\n\x06SetLED\x12\x0e.SetLEDRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_gen.blinky_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETLEDREQUEST']._serialized_start=55
  _globals['_SETLEDREQUEST']._serialized_end=96
  _globals['_BLINKSERVICE']._serialized_start=98
  _globals['_BLINKSERVICE']._serialized_end=162
# @@protoc_insertion_point(module_scope)
