# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto_gen/sensors.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'proto_gen/sensors.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto_gen/sensors.proto\x12\x07sensors\x1a\x1bgoogle/protobuf/empty.proto\"\x91\x01\n\x06Point3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\x0e\n\x01r\x18\x04 \x01(\x02H\x00\x88\x01\x01\x12\x0e\n\x01g\x18\x05 \x01(\x02H\x01\x88\x01\x01\x12\x0e\n\x01\x62\x18\x06 \x01(\x02H\x02\x88\x01\x01\x12\x16\n\tintensity\x18\x07 \x01(\rH\x03\x88\x01\x01\x42\x04\n\x02_rB\x04\n\x02_gB\x04\n\x02_bB\x0c\n\n_intensity\"T\n\x0bPointCloud3\x12\x1f\n\x06points\x18\x01 \x03(\x0b\x32\x0f.sensors.Point3\x12\x16\n\ttimestamp\x18\x02 \x01(\x04H\x00\x88\x01\x01\x42\x0c\n\n_timestamp\"w\n\x07IMUData\x12\n\n\x02\x61x\x18\x01 \x01(\x02\x12\n\n\x02\x61y\x18\x02 \x01(\x02\x12\n\n\x02\x61z\x18\x03 \x01(\x02\x12\n\n\x02gx\x18\x04 \x01(\x02\x12\n\n\x02gy\x18\x05 \x01(\x02\x12\n\n\x02gz\x18\x06 \x01(\x02\x12\x16\n\ttimestamp\x18\x07 \x01(\x04H\x00\x88\x01\x01\x42\x0c\n\n_timestamp\"`\n\x0eRecordingEntry\x12$\n\x04scan\x18\x01 \x01(\x0b\x32\x14.sensors.PointCloud3H\x00\x12\x1f\n\x03imu\x18\x02 \x01(\x0b\x32\x10.sensors.IMUDataH\x00\x42\x07\n\x05\x65ntry\"5\n\x0fsaveFileRequest\x12\x15\n\x08\x66ilename\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_filename2\xc1\x01\n\rSensorService\x12\x39\n\x07getScan\x12\x16.google.protobuf.Empty\x1a\x14.sensors.PointCloud30\x01\x12\x34\n\x06getImu\x12\x16.google.protobuf.Empty\x1a\x10.sensors.IMUData0\x01\x12?\n\x0bsavePLYScan\x12\x18.sensors.saveFileRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_gen.sensors_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POINT3']._serialized_start=66
  _globals['_POINT3']._serialized_end=211
  _globals['_POINTCLOUD3']._serialized_start=213
  _globals['_POINTCLOUD3']._serialized_end=297
  _globals['_IMUDATA']._serialized_start=299
  _globals['_IMUDATA']._serialized_end=418
  _globals['_RECORDINGENTRY']._serialized_start=420
  _globals['_RECORDINGENTRY']._serialized_end=516
  _globals['_SAVEFILEREQUEST']._serialized_start=518
  _globals['_SAVEFILEREQUEST']._serialized_end=571
  _globals['_SENSORSERVICE']._serialized_start=574
  _globals['_SENSORSERVICE']._serialized_end=767
# @@protoc_insertion_point(module_scope)
