@startuml Arch

' Set background color
skinparam backgroundColor #F5F7FA

[ MCP Server ] as MCPServer #FFF3E0
[ MCP Client ] as MCPClient #E8F5E9
[ LLM ] as LLM #F3E5F5
[ gRPC Server ] as GRPCServer #E1F5FE
[ LED ] as LED #FBE9E7
actor "User" as User

MCPClient <- User : interacts
MCPClient --> MCPServer : MCP tools, resources
LLM <- MCPClient: queries/completes
MCPServer --> GRPCServer : gRPC
GRPCServer <-> LED : set/get

package {
    [Tools] as Tools
    [Resources] as Resources
}

MCPServer -down-> Tools
MCPServer -down-> Resources

@enduml